trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
  - task: UseDotNet@2
    inputs:
      version: '3.0.x'

  - task: UseDotNet@2
    inputs:
      version: '2.2.x'
      packageType: runtime

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'config'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'src/PickAll/PickAll.csproj'
      arguments: '-c release'